name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AfkPool-jar
          path: target/*.jar